name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      # - name: Test
      #   run: go test -race -v ./...

      - name: Build
        run: |
          GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-w -s" -o build/mpv-handler.exe
          GOOS=windows GOARCH=arm64 go build -trimpath -ldflags "-w -s" -o build/mpv-handler-arm64.exe

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: build/*
          name: ${{ github.run_number }}
